namespace LoteriaMexicanaTypes.Models;

public static class Cards
{
    public record Card(int Id, string Name);

    public static IReadOnlyList<Card> All { get; } =
    [
        new(1, "El gallo"),
        new(2, "El diablito"),
        new(3, "La dama"),
        new(4, "El catrín"),
        new(5, "El paraguas"),
        new(6, "La sirena"),
        new(7, "La escalera"),
        new(8, "La botella"),
        new(9, "El barril"),
        new(10, "El árbol"),
        new(11, "El melón"),
        new(12, "El valiente"),
        new(13, "El gorrito"),
        new(14, "La muerte"),
        new(15, "La pera"),
        new(16, "La bandera"),
        new(17, "El bandolón"),
        new(18, "El violoncello"),
        new(19, "La garza"),
        new(20, "El pájaro"),
        new(21, "La mano"),
        new(22, "La bota"),
        new(23, "La luna"),
        new(24, "El cotorro"),
        new(25, "El borracho"),
        new(26, "El negrito"),
        new(27, "El corazón"),
        new(28, "La sandía"),
        new(29, "El tambor"),
        new(30, "El camarón"),
        new(31, "Las jaras"),
        new(32, "El músico"),
        new(33, "La araña"),
        new(34, "El soldado"),
        new(35, "La estrella"),
        new(36, "El cazo"),
        new(37, "El mundo"),
        new(38, "El apache"),
        new(39, "El nopal"),
        new(40, "El alacrán"),
        new(41, "La rosa"),
        new(42, "La calavera"),
        new(43, "La campana"),
        new(44, "El cantarito"),
        new(45, "El venado"),
        new(46, "El sol"),
        new(47, "La corona"),
        new(48, "La chalupa"),
        new(49, "El pino"),
        new(50, "El pescado"),
        new(51, "La palma"),
        new(52, "La maceta"),
        new(53, "El arpa"),
        new(54, "La rana")
    ];
}