namespace LoteriaMexicanaTypes.Models;

public static class Cards
{
    public record Card(int id, string name);

    public static IReadOnlyList<Card> All { get; } =
    [
        new Card(1, "El gallo"),
        new Card(2, "El diablito"),
        new Card(3, "La dama"),
        new Card(4, "El catrín"),
        new Card(5, "El paraguas"),
        new Card(6, "La sirena"),
        new Card(7, "La escalera"),
        new Card(8, "La botella"),
        new Card(9, "El barril"),
        new Card(10, "El árbol"),
        new Card(11, "El melón"),
        new Card(12, "El valiente"),
        new Card(13, "El gorrito"),
        new Card(14, "La muerte"),
        new Card(15, "La pera"),
        new Card(16, "La bandera"),
        new Card(17, "El bandolón"),
        new Card(18, "El violoncello"),
        new Card(19, "La garza"),
        new Card(20, "El pájaro"),
        new Card(21, "La mano"),
        new Card(22, "La bota"),
        new Card(23, "La luna"),
        new Card(24, "El cotorro"),
        new Card(25, "El borracho"),
        new Card(26, "El negrito"),
        new Card(27, "El corazón"),
        new Card(28, "La sandía"),
        new Card(29, "El tambor"),
        new Card(30, "El camarón"),
        new Card(31, "Las jaras"),
        new Card(32, "El músico"),
        new Card(33, "La araña"),
        new Card(34, "El soldado"),
        new Card(35, "La estrella"),
        new Card(36, "El cazo"),
        new Card(37, "El mundo"),
        new Card(38, "El apache"),
        new Card(39, "El nopal"),
        new Card(40, "El alacrán"),
        new Card(41, "La rosa"),
        new Card(42, "La calavera"),
        new Card(43, "La campana"),
        new Card(44, "El cantarito"),
        new Card(45, "El venado"),
        new Card(46, "El sol"),
        new Card(47, "La corona"),
        new Card(48, "La chalupa"),
        new Card(49, "El pino"),
        new Card(50, "El pescado"),
        new Card(51, "La palma"),
        new Card(52, "La maceta"),
        new Card(53, "El arpa"),
        new Card(54, "La rana"),
    ];
}
